name: FunPay Simplified Scraper

on:
  schedule:
    - cron: "0 */2 * * *" # Run every two hours
    - cron: "0 10 * * *" # Run at 10 AM UTC every day (adjust timezone if needed)

  workflow_dispatch: # Allow manual trigger
    inputs:
      run_mode:
        description: "Mode for the scraper (e.g., hourly, heartbeat, or custom)"
        required: true
        default: "heartbeat" # Default to 'heartbeat' if not specified
        type: string

jobs:
  scrape-and-notify-criteria:
    runs-on: ubuntu-latest
    env: # Define environment variables at the job level so all steps inherit them
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5 # Use v5 for setup-python
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: pip install requests beautifulsoup4 lxml python-dotenv

      # DEBUGGING STEP (Optional, but helpful)
      - name: Show Event Context
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Schedule: ${{ github.event.schedule }}"
          echo "Inputs: ${{ toJson(github.event.inputs) }}"

      # STEP 4: Run the scraper script (Scheduled - Hourly)
      - name: Run Simplified Scraper & Notifier - Hourly (Scheduled)
        if: github.event_name == 'schedule' && github.event.schedule == '0 */2 * * *'
        run: |
          echo "Running Scrape Every two hours cron job..."
          python funpay_scraper_simplified.py hourly

      # STEP 5: Run the scraper script (Scheduled - Heartbeat)
      - name: Run Simplified Scraper & Notifier - Heartbeat (Scheduled)
        if: github.event_name == 'schedule' && github.event.schedule == '0 10 * * *'
        run: |
          echo "Scheduled heartbeat check..."
          python funpay_scraper_simplified.py heartbeat

      # STEP 6: Run the scraper script (Manually Triggered)
      - name: Run Simplified Scraper & Notifier - Manual Trigger
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Manual testing, running with mode: ${{ github.event.inputs.run_mode }}"
          python funpay_scraper_simplified.py ${{ github.event.inputs.run_mode }}
