name: FunPay Simplified Scraper

on:
  schedule:
    - cron: "0 */2 * * *" # Run every two hours
    - cron: "0 10 * * *" # Run at 6pm every day

  workflow_dispatch: # Allow manual trigger

jobs:
  scrape-and-notify-criteria: # CHANGED: Job name reflects action
    runs-on: ubuntu-latest
    steps:
      # STEP 1: Checkout repository
      # Needed for the script
      - name: Checkout repository
        uses: actions/checkout@v4

      # STEP 2: Setup Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # Keeping Python 3.10

      # STEP 3: Install Python dependencies
      - name: Install Python dependencies
        run: pip install requests beautifulsoup4 lxml python-dotenv # Added python-dotenv

      # STEP 4: Run the scraper script
      # Script scrapes and notifies based on criteria
      - name: Run Simplified Scraper & Notifier -hourly
        env: # Pass secrets as environment variables to the Python script
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }} # Assuming secret name is DISCORD_WEBHOOK_URL
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }} # Assuming secret name is TELEGRAM_CHAT_ID
        if: github.event.schedule == '0 */2 * * *'
        run: |
          echo "Running Scrape Every two hours cron job..."
          python funpay_scraper_simplified.py hourly
      - name: Run Simplified Scraper & Notifier -heartbeat
        if: github.event.schedule == '0 10 * * *'
        run: |
          echo "Heartbeat check..."
          python funpay_scraper_simplified.py heartbeat

      - name: Run Simplified Scraper & Notifier -manual
        if: github.event.schedule == 'workflow_dispatch'
        run: |
          echo "manual testing, running on heartbeat mode..."
          python funpay_scraper_simplified.py heartbeat
