# .github/workflows/scrape.yml
name: FunPay Scraper v3.0

on:
  schedule:
    # Run every hours
    - cron: "0 */1 * * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  scrape-price-track-notify:
    runs-on: ubuntu-latest
    steps:
      # STEP 1: Checkout repository
      # Needed for script AND offer_state.json
      - name: Checkout repository
        uses: actions/checkout@v4

      # STEP 2: Setup Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # STEP 3: Install Python dependencies
      - name: Install Python dependencies
        run: pip install requests beautifulsoup4 lxml # json/urllib are standard

      # STEP 4: Run the scraper script
      # Python script handles all logic: load state, scrape, compare, notify, prepare next state
      - name: Run Python Scraper & Notifier
        env: # Pass secrets as environment variables to the Python script
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          DISCORD_WEBHOOK_URL_ENV: ${{ secrets.DISCORD_WEBHOOK_URL_ENV }}
        run: |
          echo "Running funpay_scraper.py (price tracking)..."
          python funpay_scraper_v3.py
          # Log status of the state file for verification
          echo "--- Offer State file status after script run ---"
          ls -l offer_state.json || echo "offer_state.json does not exist yet."

      # STEP 5: Commit updated offer state file if changed
      # This is CRUCIAL for remembering prices between runs
      - name: Commit offer state file
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # Add the state file specifically. Python script overwrites it.
          git add offer_state.json
          # Check if the file was actually changed or newly added
          if ! git diff --staged --quiet -- offer_state.json; then
            echo "Committing changes to offer_state.json..."
            git commit -m "Update offer price state ($(date -u +'%Y-%m-%d %H:%M:%S UTC'))"
            # Add retry logic for push
            retry_count=0
            max_retries=3
            push_success=false
            until $push_success || [ $retry_count -eq $max_retries ]; do
              retry_count=$((retry_count+1))
              if git push; then
                push_success=true
                echo "Push successful."
              else
                echo "Push failed. Retrying (${retry_count}/${max_retries})..."
                sleep 5
                rm -f .git/index.lock || true
              fi
            done
            if ! $push_success; then
              echo "Error: Failed to push offer_state.json after $max_retries retries."
              exit 1
            fi
            echo "Committed and pushed changes to offer_state.json"
          else
            echo "No changes detected in offer_state.json. Nothing to commit."
          fi
