name: FunPay Scraper
on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:      # Manual trigger

jobs:
  scrape-and-notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install requests beautifulsoup4 lxml
      - name: Run scraper
        run: |
          echo "Debug: Starting script..."
          python funpay_scraper.py > offers.txt
          echo "Debug: Script finished. Checking file..."
          ls -la offers.txt
          echo "File contents:"
          cat offers.txt
      - name: Upload offers as artifact
        uses: actions/upload-artifact@v3
        with:
          name: funpay-offers
          path: offers.txt
      - name: Send Telegram notification
        if: always()
        run: |
          if [ -s offers.txt ]; then
            MESSAGE=$(cat offers.txt)
            curl -s -X POST \
              "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
              -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
              -d "text=💰 FunPay Deals Under $50:%0A%0A$MESSAGE" 
          else
            echo "No new offers found."
          fi
